### PR TITLE
Bump version to 4.0.0

### PR DESCRIPTION
**Pull request by LaurentShala**
# Details

This PR updates the version to 4.0.0. We initially bumped it to 3.1.0 in #6, but decided to close it because #5 introduces a couple breaking changes to the Pod.

### CODE REVIEW

**Comment by jrmsklar** [comment]
Did you update the version in the project file as well?

**Comment by LaurentShala** [comment]
@jrmsklar It looks like the project file is still on version `1.0.9`. I decided to stick with minimal changes and only update the podspec.

**Comment by LaurentShala** [comment]
@jrmsklar See https://github.com/stockx/PinEntryView/pull/4/files

**Comment by jrmsklar** [comment]
I took a look at several other popular Cocoapods (Alamofire, Eureka, Siesta, and more) and it looks like a lot keep the version number in the Xcode project in the pod in sync with the one in the podspec, but not all do.

That said, I'd prefer we keep these in sync to avoid any confusions.

**Comment by LaurentShala** [comment]
@jrmsklar I agree, this should be all set

**Comment by jrmsklar** [comment]
Thanks for the update @LaurentShala!

**Pull request merged**
